#----------
# DCMQI
#----------

set(DEPENDENCIES DCMTK::DCMTK)# ITK)

ExternalProject_Add(DCMQI
    GIT_REPOSITORY https://github.com/qiicr/dcmqi.git
    GIT_TAG ea4f0809c8ba771e262a69b5f81d547a3945b264
    UPDATE_COMMAND ""
    INSTALL_COMMAND ""
    CMAKE_ARGS
        -DBUILD_SHARED_LIBS:BOOL=ON
        -DDCMQI_BUILD_APPS:BOOL=OFF
        -DDCMTK_DIR:PATH=${DCMTK_DIR}
        -DOpenJPEG_DIR:PATH=${OpenJPEG_DIR}
        -DITK_NO_IO_FACTORY_REGISTER_MANAGER:BOOL=ON
        -DDCMQI_SUPERBUILD:BOOL=OFF
    DEPENDS ${DEPENDENCIES}
)
